### ISSUE TITLE
Ungoogled on Android

### ISSUE THREAD

**Issue by nopjmp** [Eloston/ungoogled-chromium#157]
# This is on hiatus for personal reasons.

I'm creating this issue to track the progress on getting Ungoogled Chromium on Android. I'll be editing this issue with updates on what's broken and whats working.

CopperheadOS builds Chromium as part of their build process. I want to make it easy for someone to come along and import Ungoogled into their Android build system and have it "just work" on the supported operating systems for AOSP.

I'm currently waiting for parts to come in so I have a better machine to build on. Hopefully it will arrive soon.

### Tasks (WIP)

- [ ] Setup build environment
- [ ] Document requirements for Andriod to build
- [ ] Generate patches if required
- [ ] Extend current build system to support Android

### Goals

- Make it simple for someone to build their own apk.
- Be as detailed as possible to prevent future confusion from ambiguity.

I'm hoping to extend the gritty details onto other platforms, but I'm going to use Android as the test bed to work on the methodology.

**Comment by Eloston** [comment]
Hmm this is a nice issue report, but now I don't know what to do with #56. I guess I can close that one?

> Extend current build system to support Android

Should probably wait for #125.

**Comment by nopjmp** [comment]
I'll discuss it you on gitter once I'm done with family activities for the holiday.

Sent from my android device.

-----Original Message-----

**Comment by 9Morello** [comment]
@nopjmp Is it possible to add extension support to Android builds of Chromium?

**Comment by DeadSix27** [comment]
@9Morello We had that discussion before, afaik its not possible yet, unfortunately.

**Comment by nopjmp** [comment]
Extension support would require quite a bit of custom ui code and integration since nothing is supported in there. You can make a simple app that injects javascript onto a page using WebView. WebView uses Chromium under the hood for a while.

**Comment by 9Morello** [comment]
@DeadSix27 @nopjmp I see, thanks for the heads up.

**Comment by avently** [comment]
@nopjmp  any news?

**Comment by nopjmp** [comment]
Work has been busy so I haven't been able to setup a working development system. My home lab I'm building will help me get a build vm up so I can iterate fast. I'll update the main issue just in case someone else comes in later and doesn't read the entire thread.

**Comment by Driesje32** [comment]
Any progress? Guess that a ungoogled-chromium app in the F-droid repos will be beneficial for a lot of people, also on CoS.

**Comment by Eloston** [comment]
@Driesje32 This is still on a hiatus. I'm going close this and leave it closed until nopjmp decides to resume. #56 is still around if anyone wants to discuss Android support in general.
